Remove dependency on Remote
sindresorhus/electron-store pull request #157
Opened 2020-12-23 14:44 UTC by MehediH

Hi! Attempting to address #152 here.

As Electron is deprecating `remote`, this PR removes the module's dependency on remote. The change requires users to first call the new `StoreInit()` function exported by the module in the Main process in order to set up the `ipcMain` handler which enables communication from the renderer process. 

The default export, as a result, has been tweaked and the module now needs to be used as such:

```javascript
// main.js

const { Store, StoreInit } = require('electron-store');

StoreInit(); // needed for communication between Main/Renderer processes 

const store = new Store({ cwd: 'foo' });
store.set('unicorn', '🦄');
```

And on the renderer process, the usage is practically the same, except from the import:
```javascript
// renderer.js
const { Store } = require('electron-store');

const store = new Store({cwd: 'foo'});
console.log(store.get("unicorn"))
```

Happy to improve this further as needed -- will also update the docs and usage instructions if this looks good @sindresorhus!

2020-12-24 08:02 UTC, sindresorhus commented
Couldn't just `new Store()` initialize it (if it's on the main process)? Why a separate method?

The IPC communication should be synchronous.

2020-12-24 10:34 UTC, MehediH commented
Good point! I have moved the initializer into the constructor so calling `new Store()` within the main process will set up the `ipcMain` handlers. It will still throw an error if it can't find the handler for the message when called from a renderer process. 

> The IPC communication should be synchronous.

Could you please clarify how this can be achieved? I have tried `ipcRenderer.sendSync()` but that blocks the renderer process while it waits for a reply, and thus there is a noticeable delay in the app opening up. 

Would appreciate any pointers :)

2020-12-24 11:02 UTC, MehediH commented
Also, I wonder what the best approach for the initializer would be? Having a static `init()` like in [e55ebe6](https://github.com/sindresorhus/electron-store/pull/157/commits/e55ebe62d358342ef3774d65177ab9f804634274) will allow the user to set-up the `ipcMain` handlers on the Main process without actually creating the Store, in case they only need to use it in the Renderer. 

The other option like in [3fc1e35](https://github.com/sindresorhus/electron-store/pull/157/commits/3fc1e351dd95c485e3b2143343723bbb0c8d527b) will make the module work as is after the update, so I guess that is more beneficial, but that's only the case if they are creating a Store in the main process first. That will break things for those who just have a Store in the renderer process after the update, and they will need to create a Store in the main process first. 

Thoughts?

2020-12-26 09:59 UTC, sindresorhus commented
> Could you please clarify how this can be achieved? I have tried ipcRenderer.sendSync() but that blocks the renderer process while it waits for a reply, and thus there is a noticeable delay in the app opening up.

That's how it currently works though. `remote.require` uses synchronous IPC.

The problem with async is that you can get into a situation where the renderer tries to use the store before the async IPC has replied.

> Also, I wonder what the best approach for the initializer would be? Having a static init() like in e55ebe6 will allow the user to set-up the ipcMain handlers on the Main process without actually creating the Store, in case they only need to use it in the Renderer.

We could also add a static `Store.initRenderer()` or something for that case.

2020-12-26 09:59 UTC, sindresorhus commented
// @dertieran

2020-12-26 11:21 UTC, MehediH commented
> That's how it currently works though. remote.require uses synchronous IPC.

Ah, I didn't know this. Will switch to `ipcRenderer.sendSync()` with a commit soon :)

> We could also add a static Store.initRenderer() or something for that case.

Yes, so by default if the user uses the Store in the Main process, they don't have to do anything else to use it in Rendered. But if they only use it in Renderer, they will have to call the `initRenderer` on the Main. I think that makes sense, will just have to document this clearly.

Is there anything else I should tweak or anything that's blocking the merge? 😊 Will get the first two changes committed by Monday.

2020-12-26 12:16 UTC, sindresorhus commented
> Yes, so by default if the user uses the Store in the Main process, they don't have to do anything else to use it in the Renderer. But if they only use it in Renderer, they will have to call the initRenderer on the Main. I think that makes sense, will just have to document this clearly.

👍

2020-12-27 18:12 UTC, MehediH commented
Okay I just made the changes you requested @sindresorhus, also updated a bit of the README but please let me know if I should update it more to clarify things 👍🏼

2020-12-28 19:20 UTC, runyanp commented on index.js
> +				defaultCwd: app.getVersion(),
The values for `defaultCwd` and `appVersion` here seem backwards at first glance. Is that intentional?

2020-12-28 19:40 UTC, MehediH commented on index.js
> +				defaultCwd: app.getVersion(),
Nope, thank you for pointing this out!

2021-01-07 07:00 UTC, sindresorhus commented on index.js
> +		}
I think this would be more readable if you made a general function called `getFromMain` that accepts a callback where you can do return the values and if the process is already main, it would just return them directly. That way you wouldn't need to duplicate the logic to get the values.

2021-01-07 07:00 UTC, sindresorhus commented on index.js
> +		});
This should not be duplicated here. Find a way to unify the logic.

2021-01-07 07:02 UTC, sindresorhus commented on index.js
> +	static initRenderer() {
This needs to be documented in the readme and index.d.ts

2021-01-07 11:17 UTC, MehediH commented on index.js
> +		}
Hmm, I am not quite sure if that is possible. I tried unifying the code before, but because `ElectronStore` is a subclass of `Conf`, we can't call any other class functions before calling `super()`. See: https://eslint.org/docs/rules/no-this-before-super. Unless you mean a regular function that's outside the `ElectornStore` class? Would like some clarification :)

2021-01-07 11:32 UTC, sindresorhus commented on index.js
> +		}
Regular function outside the class.

2021-01-07 11:53 UTC, MehediH commented on index.js
> +	static initRenderer() {
I have unified the `ipc` code and added the documentation for `initRenderer()` to index.d.ts. However, on the readme file, where would be an appropriate place to add this? Since it is a static function and is not an instance function, Any ideas?

2021-01-08 17:09 UTC, sindresorhus requested changes

2021-01-08 17:09 UTC, sindresorhus commented on index.js
> +	ipcMain.on('electron-store-comms', event => {
```suggestion
	ipcMain.on('electron-store-get-data', event => {
```

2021-01-08 17:09 UTC, sindresorhus commented on index.js
> +const initComms = () => {
Don't use abbreviations.

2021-01-08 17:09 UTC, sindresorhus commented on index.js
> +	static initRenderer() {
Below https://github.com/sindresorhus/electron-store#openineditor as a `###` item.

2021-01-08 17:09 UTC, sindresorhus commented on index.d.ts
> +	when the user does not create a new Store in the main process
Don't hard-wrap

2021-01-08 17:09 UTC, sindresorhus commented on index.d.ts
> +	ipcRenderer(): void;
Incorrect name.

2021-01-08 17:09 UTC, sindresorhus commented on index.js
> +		return initComms();
This should not return.

2021-01-08 17:09 UTC, sindresorhus commented on readme.md
> +You can use this module directly in both the main and renderer process. For use in the renderer process, you need to create a `new Store()` in the main process, or call `Store.initRenderer()` in the
This is not the place to document "why" Electron no longer has the `remote` module.

2021-01-12 18:35 UTC, sindresorhus commented on index.d.ts
> +	Initializier that sets up the required ipcMain listener when the user does not create a new Store in the main process.
This should be in sync with the readme.

2021-01-12 18:36 UTC, sindresorhus commented on readme.md
> +Initializier to set-up the required `ipc` communication channels for the module when a `Store` instance is not created in the main process. Use this if you are using a `Store` instance in the Electro
```suggestion
Initializer to set up the required `ipc` communication channels for the module when a `Store` instance is not created in the main process. Use this if you are using a `Store` instance in the Electron renderer process only.
```

2021-01-12 18:37 UTC, sindresorhus commented on readme.md
> +console.log(store.get('unicorn'));
The code should be valid.

2021-01-12 18:37 UTC, sindresorhus commented on readme.md
> +And in the renderer process:
```suggestion
And in the renderer process:

```

2021-01-12 18:38 UTC, sindresorhus commented on readme.md
> +Initializier to set-up the required `ipc` communication channels for the module when a `Store` instance is not created in the main process. Use this if you are using a `Store` instance in the Electro
I think this could be shortened to a single sentence.

2021-01-12 18:38 UTC, sindresorhus commented on index.js
> +	// When the user does not create a new Store in the main process
This comment is moot. It's better document in the TS file.

2021-01-12 19:51 UTC, MehediH commented on readme.md
> +Initializier to set-up the required `ipc` communication channels for the module when a `Store` instance is not created in the main process. Use this if you are using a `Store` instance in the Electro
Haha yeah, sorry about that!

2021-01-13 14:15 UTC, Art4 commented
I think the mandatory call of `Store.initRenderer()` will confuse some users if they only want to use the store in the renderer. This will also lead to confusion with users who only use the store in main. We should make it clearer.

Suggestion: We are disabling support in renderer by default so the store will only work in main and support for the renderer must be explicit enabled.

### renderer is disabled by default

So the default in main will look like this:

```js
// in main
const Store = require('electron-store');

const store = new Store();
```

If someone trying to use it in renderer it should return an error.

```js
// in renderer
const Store = require('electron-store');

const store = new Store();
// ERROR: You have to active renderer integration in your main.js
```

### activate renderer integration

To active the store in the renderer one has to call the static method `enableRendererIntegration()`.

```js
// in main
const Store = require('electron-store');

Store.enableRendererIntegration();
```

```js
// in renderer
const Store = require('electron-store');

const store = new Store();

store.set('unicorn', '🦄');
console.log(store.get('unicorn'));
```

This should be an elegant an clear way to active the ipc in renderer.

What do you think?

2021-01-13 14:44 UTC, dertieran commented
I think there are many package that will have this problem.
*([7 alone from sindre](https://github.com/sindresorhus/electron-util/issues/36#issuecomment-749622810) :smile:)*

Over at `electron-util` I also took the approach of exposing a [`initializeRemote`](https://github.com/sindresorhus/electron-util/pull/37) function but didn't really like it.
May main concern was that using `@electron/remote` is somewhat discouraged.

I proposed a pattern that basically exposes a `electron-util/main` and `electron-util/renderer` module.
The `main` module containing code that needs to be executed in `main` process and vice versa for the `renderer` module.
*(Of Course there can also be shared code between those, that can run in either the `main` or `renderer` process.)*
Then the developer can decide if they want to expose the `main` process module to the renderer by using the `@electron/remote` themself.

Would be great to get input on this idea by other developers who also are facing this problem.
Because I personally use most of these package in the `main` process only, so I only know this use case.
We can also discuss this in https://github.com/sindresorhus/electron-util/issues/36 and this PR can be keept as is.

2021-01-13 15:17 UTC, Art4 commented
@dertieran This PR will remove the dependency for the remote module. Splitting the repo for main and renderer seems a bit over engineered to me.
I'm not sure if your comment was meant for this issue/repo... 🤔

2021-01-13 15:37 UTC, dertieran commented
> @dertieran This PR will remove the dependency for the remote module. Splitting the repo for main and renderer seems a bit over engineered to me.

Oh might by my bad, just came here because sindre mentioned me and didn't look through the code completely.
Might have misunderstood why I was mentioned :sweat_smile: 

My suggestion basically is, if the package needs functionality the app developer needs to handle the how  they want to use it from the renderer.
But I guess if only some functionality is needed from the `main` process a solution like this is also a good idea.

Maybe this is really offtopic here, because the changes for this package are more minimal.

2021-01-22 17:03 UTC, merged