Flagging Initialisation Data Listener
sindresorhus/electron-store pull request #180
Opened 2021-04-06 02:30 UTC by rroessler

On each construction of an ElectronStore instance, the initDataListener method is called. This causes duplicate ipcMain handlers for the 'electron-store-get-data' channel. Found that this causes an Electron EventEmitter warning of 'MaxListenersExceededWarning'. By setting an initialiser flag, events are handled as needed and does not cause this warning. Additionally if someone were to properly exceed this (in my case I was at 11), by dynamically creating larger amounts of stores (which could be possible in larger scale applications, although not recommended), this could have dangerous and odd side-effects.

2021-04-06 07:44 UTC, sindresorhus requested changes

2021-04-06 07:44 UTC, sindresorhus commented on index.js
> +const flags = {initalised: false};
I don't really see the point in putting it in an object.

Name should be: `isInitialized`

2021-04-06 21:47 UTC, rroessler commented on index.js
> +const flags = {initalised: false};
No worries, didn't know whether the library required const variables in the global scope. Regardless, changed it to `isInitialised` now.

2021-04-07 04:47 UTC, sindresorhus commented
Re https://github.com/sindresorhus/electron-store/pull/180#discussion_r607608721, you did not correctly copy the name I wrote.

2021-04-07 04:47 UTC, sindresorhus commented on index.js
> +let isInitialised = false;
```suggestion

let isInitialized = false;
```

2021-04-07 05:34 UTC, rroessler commented on index.js
> +let isInitialised = false;
Hi, I can do that for you however either spelling should be fine (as the variant with 's' is the common version within British and Australian English).

2021-04-07 08:45 UTC, merged